import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useEffect, useState } from 'react';

type FAQ = {
  id: number
  attributes: {
    Title: string
    Body: string
  }
}

const Home: NextPage = () => {
  const [faqs, setFaqs] = useState([]);
  useEffect(() => {
    axios.get("http://localhost:1337/api/faqs").then(result => {
      setFaqs(result.data.data);
    })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {faqs.map((faq: FAQ) => (<div key={faq.id} className={styles.faq_item}>
            <div className={styles.faq_title}>{faq.attributes.Title}</div>
            <div className={styles.faq_body}>{faq.attributes.Body}</div>
        </div>))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
